# Generated by Django 5.1.1 on 2026-07-01 14:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=3)),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=api.models._utcnow)),
                ('verificado', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('transfer_codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('transfer_codigo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('transfer_destino_alias', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_moneda', models.CharField(blank=True, max_length=3, null=True)),
                ('transfer_monto', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('moneda', models.CharField(max_length=3)),
                ('fecha', models.DateTimeField(default=api.models._utcnow)),
                ('estado', models.CharField(default='completada', max_length=20)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='api.cuenta')),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origen', to='api.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(default=api.models._utcnow)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='api.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='cuenta',
            unique_together={('usuario', 'moneda')},
        ),
    ]
