spring:
  application:
    name: backend-billetera

  datasource:
    url: jdbc:postgresql://localhost:5432/billetera_virtual
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false

